;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.CounterTerror",DevComment="")
+GameplayTagList=(Tag="Character.Terrorist",DevComment="")
+GameplayTagList=(Tag="Menu",DevComment="")
+GameplayTagList=(Tag="Team.CounterTerror",DevComment="")
+GameplayTagList=(Tag="Team.Terrorist",DevComment="")
+GameplayTagList=(Tag="UI.Crosshair",DevComment="")
+GameplayTagList=(Tag="UI.Main",DevComment="mainMenu")
+GameplayTagList=(Tag="UI.Menu",DevComment="")
+GameplayTagList=(Tag="UI.Single",DevComment="")
+GameplayTagList=(Tag="UI.Team",DevComment="")
+GameplayTagList=(Tag="UI.TeamSelection",DevComment="")

